#define WIN32_LEAN_AND_MEAN

//-DIMENSOES-//
#define W_MAINWINDOW 1280
#define H_MAINWINDOW 720
#define W_BTTN 200
#define H_BTTN 200

//-ID DOS BOTOES-//
#define BTTN_MAIN_EXCORTE					0101
#define BTTN_MAIN_EXVENDA					0201
#define BTTN_MAIN_RELATORIO					0301
#define BTTN_DBOX_EXCORTE_CONF				0102

//-ID DOS MENUS-//
#define HMENU_MAIN_BARBEIRO					0401
#define HMENU_MAIN_CORTE					0501
#define HMENU_MAIN_VENDA					0601

//-ID DAS DIALOG BOXES-//
#define DBOX_MAIN_EXCORTE					0701
#define DBOX_MAIN_EXVENDA					0801
#define DBOX_MAIN_RELATORIO					0901

//-ID DAS LISTAS DE ROLAGENS VERTICAIS-//
#define LIST_DBOX_EXCORTE_BARBEIROS			0202



